// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginPrettier from 'eslint-plugin-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      // Build output and dependencies, matched at any depth: the `apps/*`
      // workspaces have their own, and `.claude/worktrees/*` holds full copies
      // of this repo whose generated files are not this checkout's source.
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      '**/web-build/**',
      // Claude Code state, including the worktrees it creates. All gitignored.
      '.claude/**',
      // Generated by `npm run db:types`; regenerate rather than edit.
      '**/db/types.generated.ts',
      // Supabase CLI working directories.
      '**/supabase/.temp/**',
      '**/supabase/.branches/**',
      // Expo generated output.
      '**/.expo/**',
      '**/expo-env.d.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      prettier: eslintPluginPrettier,
    },
    rules: {
      'prettier/prettier': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  eslintConfigPrettier,
);
