packages:
  - '.'
  - 'apps/*'

allowBuilds:
  '@scarf/scarf': false
  esbuild: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.22'
  - '@expo/ui@57.0.16'
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo-router@57.0.19
  - expo@57.0.20
